#!/usr/bin/env python3
"""Aetheria proto → GDScript codegen.

Reads shared/proto/*.proto, emits one GDScript class per message into
client/scripts/proto/generated/. Supports the proto3 subset the client needs:
int32/int64/uint32/uint64/bool/string/bytes/message + enums. Wire types follow
ProtoWire.gd. See ADR-003.

Usage: python3 tools/protogen/protogen.py [--proto-dir shared/proto] [--out client/scripts/proto/generated]
"""
import argparse
import re
from pathlib import Path

FIELD_RE = re.compile(r"\s*(repeated\s+)?([A-Za-z][A-Za-z0-9_.]*)\s+([A-Za-z_][A-Za-z0-9_]*)\s*=\s*(\d+)\s*;")
MSG_RE = re.compile(r"message\s+([A-Za-z][A-Za-z0-9_]*)\s*\{")
ENUM_RE = re.compile(r"enum\s+([A-Za-z][A-Za-z0-9_]*)\s*\{")

SCALAR_GD = {
    "int32": "int", "int64": "int", "uint32": "int", "uint64": "int",
    "bool": "bool", "string": "String", "bytes": "PackedByteArray",
}
ENUM_GD = "int"
VARINT_TYPES = {"int32", "int64", "uint32", "uint64", "bool"}
WIRE_TYPES = {"float": 5, "double": 1}  # unused in MVP, listed for completeness

GD_RESERVED = {"class_name", "extends", "static", "var", "func", "if", "else", "match", "return", "break"}


def gd_name(name: str) -> str:
    return "_" + name if name in GD_RESERVED else name


def emit_message(msg_name: str, fields: list, out: Path) -> None:
    lines = [
        f"# GENERATED by tools/protogen/protogen.py from shared/proto. DO NOT EDIT.",
        f"# Wire format per ProtoWire.gd (see docs/adr/003-proto-codegen.md).",
        f"extends RefCounted",
        f"class_name {msg_name}",
        "",
    ]
    for f in fields:
        gd = SCALAR_GD.get(f["type"])
        if gd is None:
            gd = "PackedByteArray"  # nested message → embedded bytes, decoded by caller
        decl = gd if not f["repeated"] else "Array"
        lines.append(f"var {gd_name(f['name'])}: {decl} = {[] if f['repeated'] else _zero_value(gd)}")
    lines.append("")

    # encode
    lines.append(f"func encode() -> PackedByteArray:")
    lines.append(f"\tvar w := ProtoWire.new()")
    for f in fields:
        gd = SCALAR_GD.get(f["type"], "PackedByteArray")
        v = gd_name(f["name"])
        if f["repeated"]:
            lines.append(f"\tfor item in {v}:")
            _emit_write(lines, "item", f, gd, 2)
        else:
            _emit_write(lines, v, f, gd, 1)
    lines.append(f"\treturn w.buf")
    lines.append("")

    # decode
    lines.append(f"static func decode(data: PackedByteArray) -> {msg_name}:")
    lines.append(f"\tvar m := {msg_name}.new()")
    lines.append(f"\tvar w := ProtoWire.new()")
    lines.append(f"\tw.buf = data")
    lines.append(f"\twhile true:")
    lines.append(f"\t\tvar f := w.next_field()")
    lines.append(f"\t\tif f[0] < 0: break")
    lines.append(f"\t\tmatch f[0]:")
    seen = set()
    for f in fields:
        if f["num"] in seen:
            continue
        seen.add(f["num"])
        gd = SCALAR_GD.get(f["type"], "PackedByteArray")
        v = gd_name(f["name"])
        lines.append(f"\t\t\t{f['num']}:")
        if gd == "String":
            lines.append(f"\t\t\t\tm.{v} = w.read_string()")
        elif gd == "PackedByteArray":
            lines.append(f"\t\t\t\tm.{v} = w.read_bytes(w.read_varint())")
        elif gd == "bool":
            lines.append(f"\t\t\t\tm.{v} = w.read_varint() != 0")
        else:
            lines.append(f"\t\t\t\tm.{v} = w.read_varint()")
    lines.append(f"\t\t\t_:")
    lines.append(f"\t\t\t\tw.skip(f[1])")
    lines.append("")
    lines.append(f"\treturn m")
    lines.append("")
    out.write_text("\n".join(lines))


def _emit_write(lines: list, v: str, f: dict, gd: str, indent: int) -> None:
    pad = "\t" * indent
    num = f["num"]
    if gd == "String":
        lines.append(f"{pad}w.write_string_field({num}, {v})")
    elif gd == "PackedByteArray":
        lines.append(f"{pad}w.write_bytes_field({num}, {v})")
    elif gd == "bool":
        lines.append(f"{pad}w.write_int64_field({num}, 1 if {v} else 0)")
    else:
        lines.append(f"{pad}w.write_int64_field({num}, {v})")


def _zero_value(gd: str):
    return "false" if gd == "bool" else ("\"\"" if gd == "String" else ("PackedByteArray()" if gd == "PackedByteArray" else "0"))


def parse_proto(text: str) -> dict:
    messages = {}
    enums = {e.group(1) for e in ENUM_RE.finditer(text)}
    for m in MSG_RE.finditer(text):
        name = m.group(1)
        body = text[m.end():]
        # find matching closing brace of THIS message (depth counts { })
        depth = 1
        i = 0
        while depth > 0 and i < len(body):
            if body[i] == "{":
                depth += 1
            elif body[i] == "}":
                depth -= 1
            i += 1
        seg = body[:i]
        fields = []
        for fm in FIELD_RE.finditer(seg):
            ftype = fm.group(2)
            if ftype in enums:
                ftype = "int32"
            fields.append({
                "repeated": bool(fm.group(1)),
                "type": ftype,
                "name": fm.group(3),
                "num": int(fm.group(4)),
            })
        messages[name] = fields
    return messages


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--proto-dir", default="shared/proto")
    ap.add_argument("--out", default="client/scripts/proto/generated")
    args = ap.parse_args()

    proto_dir = Path(args.proto_dir)
    out = Path(args.out)
    out.mkdir(parents=True, exist_ok=True)

    for proto in sorted(proto_dir.glob("*.proto")):
        msgs = parse_proto(proto.read_text())
        for name, fields in msgs.items():
            emit_message(name, fields, out / f"{name}.gd")
            print(f"generated {name} ({len(fields)} fields)")


if __name__ == "__main__":
    main()
